---
- name: Load OS specific variables
  ansible.builtin.include_vars: "{{ item }}"
  tags:
    - always
    - install
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install packages
  ansible.builtin.include_tasks: install.yml

- name: Configure Certbot
  ansible.builtin.include_tasks: configure.yml

- name: Issue certificates
  ansible.builtin.include_tasks: issue.yml
